---
title: "Formatting with writeData and writeDataTable"
author: "AT"
date: "2023-07-03"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(openxlsx)
```

## data.frame to write

```{r}
df_to_format <- data.frame("Date" = Sys.Date()-0:4,
                 "Logical" = c(TRUE, FALSE, TRUE, TRUE, FALSE),
                 "Currency" = paste("$",-2:2),
                 "Accounting" = -2:2,
                 "hLink" = "https://CRAN.R-project.org/", 
                 "Percentage" = seq(-1, 1, length.out=5),
                 "TinyNumber" = runif(5) / 1E9, stringsAsFactors = FALSE)

class(df_to_format$Currency) <- "currency"
class(df_to_format$Accounting) <- "accounting"
class(df_to_format$hLink) <- "hyperlink"
class(df_to_format$Percentage) <- "percentage"
class(df_to_format$TinyNumber) <- "scientific"

## Formatting can be applied simply through the write functions
## global options can be set to further simplify things
options("openxlsx.borderStyle" = "thin")
options("openxlsx.borderColour" = "#4F81BD")
```


## create a workbook and add a worksheet

```{r}
# create workbook
wb_format <- createWorkbook()
# create worksheet
addWorksheet(wb_format, "writeData auto-formatting")

writeData(wb = wb_format, sheet = 1, x = df_to_format, startRow = 2, startCol = 2)
writeData(wb = wb_format, sheet = 1, x = df_to_format, startRow = 9, startCol = 2, borders = "surrounding")
writeData(wb = wb_format, sheet = 1, x = df_to_format, startRow = 16, startCol = 2, borders = "rows")
writeData(wb = wb_format, sheet = 1, x = df_to_format, startRow = 23, startCol = 2, borders = "columns")
writeData(wb = wb_format, sheet = 1, x = df_to_format, startRow = 30, startCol = 2, borders = "all")

## headerStyles

hs1_formatting <- createStyle(fgFill = "#4F81BD", halign = "CENTER", textDecoration = "Bold", border = "Bottom", fontColour = "white")

writeData(wb = wb_format, sheet = 1, x = df_to_format, startRow = 16, startCol = 10, headerStyle = hs1_formatting, borders = "rows", borderStyle = "medium")

## to change the display text for a hyperlink column just write over those cells

writeData(wb = wb_format, sheet = 1, x = paste("Hyperlink", 1:5), startRow = 17, startCol = 14)

## writing as an Excel Table

addWorksheet(wb_format, "writeDataTable")

writeDataTable(wb = wb_format, sheet = 2, x = df_to_format, startRow = 2, startCol = 2)
writeDataTable(wb = wb_format, sheet = 2, x = df_to_format, startRow = 9, startCol = 2, tableStyle = "TableStyleLight9")
writeDataTable(wb = wb_format, sheet = 2, x = df_to_format, startRow = 16, startCol = 2, tableStyle = "TableStyleLight2")
writeDataTable(wb = wb_format, sheet = 2, x = df_to_format, startRow = 23, startCol = 2, tableStyle = "TableStyleMedium21")

# loading styles from another file

template_file <- loadWorkbook("support_files/MSNA2022_Livelihood_tables.xlsx")

template_styles <- getStyles(template_file)

hs2_formatting <- createStyle(fgFill = "#EE5859", halign = "CENTER", textDecoration = "Bold", border = "Bottom", fontColour = "white")

writeDataTable(wb = wb_format, sheet = 2, x = df_to_format, startRow = 30, startCol = 2, tableStyle = "TableStyleMedium21", headerStyle = hs2_formatting)

# openXL(wb_format) ## opens a temp version

saveWorkbook(wb_format, "outputs/testing_formatting_openxls.xlsx", overwrite = TRUE)
```



